/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as FrontPageImport } from './routes/front-page'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const FrontPageRoute = FrontPageImport.update({
  id: '/front-page',
  path: '/front-page',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/front-page': {
      id: '/front-page'
      path: '/front-page'
      fullPath: '/front-page'
      preLoaderRoute: typeof FrontPageImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/front-page': typeof FrontPageRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/front-page': typeof FrontPageRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/front-page': typeof FrontPageRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/front-page'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/front-page'
  id: '__root__' | '/' | '/front-page'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FrontPageRoute: typeof FrontPageRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FrontPageRoute: FrontPageRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/front-page"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/front-page": {
      "filePath": "front-page.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
