name: Github Actions for FTP access
on:
 push:
  branches: ['main']
jobs:
  ftp-deploy:
    name: Deploy to FTP server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code - taking code from GitHub
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install Bun dependencies
        run: bun install
      - name: Build
        run: bun run build
      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ./www/production/
          security: strict
          port: ${{ secrets.FTP_PORT }}
          exclude: |
            src/**
            .output/**
            .github/**
            .vscode/**
            **/node_modules/**
            **/.git*
            **/.git*/**